# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://cyyeh.github.io/nbdev_101/"

git_url = "https://github.com/cyyeh/nbdev_101/tree/master/"

def custom_doc_links(name): return None
